import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "../styles/globals.css";

import { League_Spartan } from "next/font/google";
// import { cn } from "@/lib/utils";

const spartan = League_Spartan({ subsets: ["latin"], variable: "--spartan" });

// const inter = Inter({ subsets: ["latin"] });

import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${spartan.className} bg-c-background`}>
				<div className="flex items-center justify-between p-4 bg-slate-700 lg:fixed lg:h-full lg:flex-col">
					<Link href="/">
						<Image
							src="/assets/logo.svg"
							width={28}
							height={26}
							alt="Invoice App Logo"></Image>
					</Link>
					<Avatar>
						<AvatarImage src="/assets/image-avatar.jpg" />
						<AvatarFallback>CN</AvatarFallback>
					</Avatar>
				</div>
				{children}
			</body>
		</html>
	);
}
